apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder1
  namespace: argocd-poc
spec:
  project: default
  source:
    repoURL: 'https://github.com/manojchappidi/argocd-apps.git'
    path: coder
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: ghcr.io/coder/coder
        - name: image.tag
          value: v2.29.5
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
