apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder-2
  namespace: argocd-poc
spec:
  project: default
  source:
    repoURL: 'https://github.com/manojchappidi/argocd-apps.git'
    targetRevision: main
    path: 'coder'             # folder containing Chart.yaml and values.yml
    helm:
      valueFiles:
        - values.yml          # local values file in coder/ folder
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
