apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd-poc
spec:
  project: default
  source:
    repoURL: 'https://github.com/manojchappidi/argocd-apps.git'       # Replace with your Git repo URL
    chart: coder
    targetRevision: 2.29.5
    helm:
      valueFiles:
        - coder/values.yaml                # Path relative to repo root
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""                            # core API group
      kind: Service
      name: coder
      jsonPointers:
        - /spec/ports/0/nodePort
