apiVersion: v1
kind: Service
metadata:
  name: coder
  namespace: argocd-poc
  labels:
    app: coder
spec:
  type: LoadBalancer
  selector:
    app: coder
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
