coder:
  env:
    - name: CODER_ACCESS_URL
      value: "http://$(MINIKUBE_IP):30000"
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
