service:
  type: LoadBalancer

coder:
  env:
    - name: CODER_ACCESS_URL
      value: "http://localhost:3000"

    - name: CODER_PG_CONNECTION_URL
      value: "postgresql://coder:coder@postgres:5432/coder?sslmode=disable"

  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
